// Package twilio provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/faetools/devtool version (devel) DO NOT EDIT.
package twilio

// User defines model for User.
type User struct {
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

// UserResponse defines model for UserResponse.
type UserResponse User

// UserAddJSONBody defines parameters for UserAdd.
type UserAddJSONBody User

// UserAddJSONRequestBody defines body for UserAdd for application/json ContentType.
type UserAddJSONRequestBody UserAddJSONBody
