// Package bulkexports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/faetools/devtool version (devel) DO NOT EDIT.
package bulkexports

const (
	AccountSid_authTokenScopes = "accountSid_authToken.Scopes"
)

// BulkexportsV1Export defines model for bulkexports.v1.export.
type BulkexportsV1Export struct {
	// Nested resource URLs.
	Links *map[string]interface{} `json:"links"`

	// The type of communication – Messages, Calls, Conferences, and Participants
	ResourceType *string `json:"resource_type"`

	// The URL of this resource.
	Url *string `json:"url"`
}

// BulkexportsV1ExportDay defines model for bulkexports.v1.export.day.
type BulkexportsV1ExportDay struct {
	// The date when resource is created
	CreateDate *string `json:"create_date"`

	// The date of the data in the file
	Day *string `json:"day"`

	// The friendly name specified when creating the job
	FriendlyName *string `json:"friendly_name"`

	// The type of communication – Messages, Calls, Conferences, and Participants
	ResourceType *string `json:"resource_type"`

	// Size of the file in bytes
	Size *int `json:"size"`
}

// BulkexportsV1ExportDayInstance defines model for bulkexports.v1.export.day-instance.
type BulkexportsV1ExportDayInstance struct {
	RedirectTo *string `json:"redirect_to"`
}

// BulkexportsV1ExportExportCustomJob defines model for bulkexports.v1.export.export_custom_job.
type BulkexportsV1ExportExportCustomJob struct {
	// The details of a job state which is an object that contains a `status` string, a day count integer, and list of days in the job
	Details *map[string]interface{} `json:"details"`

	// The optional email to send the completion notification to
	Email *string `json:"email"`

	// The end day for the custom export specified as a string in the format of yyyy-MM-dd. This will be the last day exported. For instance, to export a single day, choose the same day for start and end day. To export the first 4 days of July, you would set the start date to 2020-07-01 and the end date to 2020-07-04. The end date must be the UTC day before yesterday.
	EndDay *string `json:"end_day"`

	// this is the time estimated until your job is complete. This is calculated each time you request the job list. The time is calculated based on the current rate of job completion (which may vary) and your job queue position
	EstimatedCompletionTime *string `json:"estimated_completion_time"`

	// The friendly name specified when creating the job
	FriendlyName *string `json:"friendly_name"`

	// This is the job position from the 1st in line. Your queue position will never increase. As jobs ahead of yours in the queue are processed, the queue position number will decrease
	JobQueuePosition *string `json:"job_queue_position"`

	// The unique job_sid returned when the custom export was created. This can be used to look up the status of the job.
	JobSid *string `json:"job_sid"`

	// The type of communication – Messages, Calls, Conferences, and Participants
	ResourceType *string `json:"resource_type"`

	// The start day for the custom export specified as a string in the format of yyyy-MM-dd
	StartDay *string `json:"start_day"`

	// This is the method used to call the webhook
	WebhookMethod *string `json:"webhook_method"`

	// The optional webhook url called on completion
	WebhookUrl *string `json:"webhook_url"`
}

// BulkexportsV1ExportJob defines model for bulkexports.v1.export.job.
type BulkexportsV1ExportJob struct {
	// The details of a job state which is an object that contains a `status` string, a day count integer, and list of days in the job
	Details *map[string]interface{} `json:"details"`

	// The optional email to send the completion notification to
	Email *string `json:"email"`

	// The end time for the export specified when creating the job
	EndDay *string `json:"end_day"`

	// this is the time estimated until your job is complete. This is calculated each time you request the job list. The time is calculated based on the current rate of job completion (which may vary) and your job queue position
	EstimatedCompletionTime *string `json:"estimated_completion_time"`

	// The friendly name specified when creating the job
	FriendlyName *string `json:"friendly_name"`

	// This is the job position from the 1st in line. Your queue position will never increase. As jobs ahead of yours in the queue are processed, the queue position number will decrease
	JobQueuePosition *string `json:"job_queue_position"`

	// The job_sid returned when the export was created
	JobSid *string `json:"job_sid"`

	// The type of communication – Messages, Calls, Conferences, and Participants
	ResourceType *string `json:"resource_type"`

	// The start time for the export specified when creating the job
	StartDay *string `json:"start_day"`
	Url      *string `json:"url"`

	// This is the method used to call the webhook
	WebhookMethod *string `json:"webhook_method"`

	// The optional webhook url called on completion
	WebhookUrl *string `json:"webhook_url"`
}

// BulkexportsV1ExportConfiguration defines model for bulkexports.v1.export_configuration.
type BulkexportsV1ExportConfiguration struct {
	// Whether files are automatically generated
	Enabled *bool `json:"enabled"`

	// The type of communication – Messages, Calls, Conferences, and Participants
	ResourceType *string `json:"resource_type"`

	// The URL of this resource.
	Url *string `json:"url"`

	// Whether to GET or POST to the webhook url
	WebhookMethod *string `json:"webhook_method"`

	// URL targeted at export
	WebhookUrl *string `json:"webhook_url"`
}

// ListDayParams defines parameters for ListDay.
type ListDayParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}

// ListExportCustomJobParams defines parameters for ListExportCustomJob.
type ListExportCustomJobParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}
