// Package accounts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/faetools/devtool version (devel) DO NOT EDIT.
package accounts

import (
	"time"
)

const (
	AccountSid_authTokenScopes = "accountSid_authToken.Scopes"
)

// AccountsV1AuthTokenPromotion defines model for accounts.v1.auth_token_promotion.
type AccountsV1AuthTokenPromotion struct {
	// The SID of the Account that the secondary Auth Token was created for
	AccountSid *string `json:"account_sid"`

	// The promoted Auth Token
	AuthToken *string `json:"auth_token"`

	// The ISO 8601 formatted date and time in UTC when the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The ISO 8601 formatted date and time in UTC when the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The URI for this resource, relative to `https://accounts.twilio.com`
	Url *string `json:"url"`
}

// AccountsV1CredentialCredentialAws defines model for accounts.v1.credential.credential_aws.
type AccountsV1CredentialCredentialAws struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid"`

	// The RFC 2822 date and time in GMT when the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The RFC 2822 date and time in GMT when the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The string that you assigned to describe the resource
	FriendlyName *string `json:"friendly_name"`

	// The unique string that identifies the resource
	Sid *string `json:"sid"`

	// The URI for this resource, relative to `https://accounts.twilio.com`
	Url *string `json:"url"`
}

// AccountsV1CredentialCredentialPublicKey defines model for accounts.v1.credential.credential_public_key.
type AccountsV1CredentialCredentialPublicKey struct {
	// The SID of the Account that created the Credential that the PublicKey resource belongs to
	AccountSid *string `json:"account_sid"`

	// The RFC 2822 date and time in GMT when the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The RFC 2822 date and time in GMT when the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The string that you assigned to describe the resource
	FriendlyName *string `json:"friendly_name"`

	// The unique string that identifies the resource
	Sid *string `json:"sid"`

	// The URI for this resource, relative to `https://accounts.twilio.com`
	Url *string `json:"url"`
}

// AccountsV1SecondaryAuthToken defines model for accounts.v1.secondary_auth_token.
type AccountsV1SecondaryAuthToken struct {
	// The SID of the Account that the secondary Auth Token was created for
	AccountSid *string `json:"account_sid"`

	// The ISO 8601 formatted date and time in UTC when the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The ISO 8601 formatted date and time in UTC when the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The generated secondary Auth Token
	SecondaryAuthToken *string `json:"secondary_auth_token"`

	// The URI for this resource, relative to `https://accounts.twilio.com`
	Url *string `json:"url"`
}

// ListCredentialAwsParams defines parameters for ListCredentialAws.
type ListCredentialAwsParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}

// ListCredentialPublicKeyParams defines parameters for ListCredentialPublicKey.
type ListCredentialPublicKeyParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}
