// Package voice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/faetools/devtool version (devel) DO NOT EDIT.
package voice

import (
	"time"
)

const (
	AccountSid_authTokenScopes = "accountSid_authToken.Scopes"
)

// Defines values for VoiceV1ByocTrunkStatusCallbackMethod.
const (
	VoiceV1ByocTrunkStatusCallbackMethodDELETE VoiceV1ByocTrunkStatusCallbackMethod = "DELETE"
	VoiceV1ByocTrunkStatusCallbackMethodGET    VoiceV1ByocTrunkStatusCallbackMethod = "GET"
	VoiceV1ByocTrunkStatusCallbackMethodHEAD   VoiceV1ByocTrunkStatusCallbackMethod = "HEAD"
	VoiceV1ByocTrunkStatusCallbackMethodPATCH  VoiceV1ByocTrunkStatusCallbackMethod = "PATCH"
	VoiceV1ByocTrunkStatusCallbackMethodPOST   VoiceV1ByocTrunkStatusCallbackMethod = "POST"
	VoiceV1ByocTrunkStatusCallbackMethodPUT    VoiceV1ByocTrunkStatusCallbackMethod = "PUT"
)

// Defines values for VoiceV1ByocTrunkVoiceFallbackMethod.
const (
	VoiceV1ByocTrunkVoiceFallbackMethodDELETE VoiceV1ByocTrunkVoiceFallbackMethod = "DELETE"
	VoiceV1ByocTrunkVoiceFallbackMethodGET    VoiceV1ByocTrunkVoiceFallbackMethod = "GET"
	VoiceV1ByocTrunkVoiceFallbackMethodHEAD   VoiceV1ByocTrunkVoiceFallbackMethod = "HEAD"
	VoiceV1ByocTrunkVoiceFallbackMethodPATCH  VoiceV1ByocTrunkVoiceFallbackMethod = "PATCH"
	VoiceV1ByocTrunkVoiceFallbackMethodPOST   VoiceV1ByocTrunkVoiceFallbackMethod = "POST"
	VoiceV1ByocTrunkVoiceFallbackMethodPUT    VoiceV1ByocTrunkVoiceFallbackMethod = "PUT"
)

// Defines values for VoiceV1ByocTrunkVoiceMethod.
const (
	VoiceV1ByocTrunkVoiceMethodDELETE VoiceV1ByocTrunkVoiceMethod = "DELETE"
	VoiceV1ByocTrunkVoiceMethodGET    VoiceV1ByocTrunkVoiceMethod = "GET"
	VoiceV1ByocTrunkVoiceMethodHEAD   VoiceV1ByocTrunkVoiceMethod = "HEAD"
	VoiceV1ByocTrunkVoiceMethodPATCH  VoiceV1ByocTrunkVoiceMethod = "PATCH"
	VoiceV1ByocTrunkVoiceMethodPOST   VoiceV1ByocTrunkVoiceMethod = "POST"
	VoiceV1ByocTrunkVoiceMethodPUT    VoiceV1ByocTrunkVoiceMethod = "PUT"
)

// VoiceV1ByocTrunk defines model for voice.v1.byoc_trunk.
type VoiceV1ByocTrunk struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid"`

	// Whether Caller ID Name (CNAM) lookup is enabled for the trunk
	CnamLookupEnabled *bool `json:"cnam_lookup_enabled"`

	// Origination Connection Policy (to your Carrier)
	ConnectionPolicySid *string `json:"connection_policy_sid"`

	// The RFC 2822 date and time in GMT that the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The RFC 2822 date and time in GMT that the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The string that you assigned to describe the resource
	FriendlyName *string `json:"friendly_name"`

	// The SID of the SIP Domain that should be used in the `From` header of originating calls
	FromDomainSid *string `json:"from_domain_sid"`

	// The unique string that identifies the resource
	Sid *string `json:"sid"`

	// The HTTP method we use to call status_callback_url
	StatusCallbackMethod *VoiceV1ByocTrunkStatusCallbackMethod `json:"status_callback_method"`

	// The URL that we call with status updates
	StatusCallbackUrl *string `json:"status_callback_url"`

	// The absolute URL of the resource
	Url *string `json:"url"`

	// The HTTP method used with voice_fallback_url
	VoiceFallbackMethod *VoiceV1ByocTrunkVoiceFallbackMethod `json:"voice_fallback_method"`

	// The URL we call when an error occurs while executing TwiML
	VoiceFallbackUrl *string `json:"voice_fallback_url"`

	// The HTTP method to use with voice_url
	VoiceMethod *VoiceV1ByocTrunkVoiceMethod `json:"voice_method"`

	// The URL we call when receiving a call
	VoiceUrl *string `json:"voice_url"`
}

// The HTTP method we use to call status_callback_url
type VoiceV1ByocTrunkStatusCallbackMethod string

// The HTTP method used with voice_fallback_url
type VoiceV1ByocTrunkVoiceFallbackMethod string

// The HTTP method to use with voice_url
type VoiceV1ByocTrunkVoiceMethod string

// VoiceV1ConnectionPolicy defines model for voice.v1.connection_policy.
type VoiceV1ConnectionPolicy struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid"`

	// The RFC 2822 date and time in GMT when the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The RFC 2822 date and time in GMT when the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The string that you assigned to describe the resource
	FriendlyName *string `json:"friendly_name"`

	// The URLs of related resources
	Links *map[string]interface{} `json:"links"`

	// The unique string that identifies the resource
	Sid *string `json:"sid"`

	// The absolute URL of the resource
	Url *string `json:"url"`
}

// VoiceV1ConnectionPolicyConnectionPolicyTarget defines model for voice.v1.connection_policy.connection_policy_target.
type VoiceV1ConnectionPolicyConnectionPolicyTarget struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid"`

	// The SID of the Connection Policy that owns the Target
	ConnectionPolicySid *string `json:"connection_policy_sid"`

	// The RFC 2822 date and time in GMT when the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The RFC 2822 date and time in GMT when the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// Whether the target is enabled
	Enabled *bool `json:"enabled"`

	// The string that you assigned to describe the resource
	FriendlyName *string `json:"friendly_name"`

	// The relative importance of the target
	Priority *int `json:"priority"`

	// The unique string that identifies the resource
	Sid *string `json:"sid"`

	// The SIP address you want Twilio to route your calls to
	Target *string `json:"target"`

	// The absolute URL of the resource
	Url *string `json:"url"`

	// The value that determines the relative load the Target should receive compared to others with the same priority
	Weight *int `json:"weight"`
}

// VoiceV1DialingPermissionsDialingPermissionsCountry defines model for voice.v1.dialing_permissions.dialing_permissions_country.
type VoiceV1DialingPermissionsDialingPermissionsCountry struct {
	// The name of the continent in which the country is located
	Continent *string `json:"continent"`

	// The E.164 assigned country codes(s)
	CountryCodes *[]string `json:"country_codes"`

	// Whether dialing to high-risk special services numbers is enabled
	HighRiskSpecialNumbersEnabled *bool `json:"high_risk_special_numbers_enabled"`

	// Whether dialing to high-risk toll fraud numbers is enabled, else `false`
	HighRiskTollfraudNumbersEnabled *bool `json:"high_risk_tollfraud_numbers_enabled"`

	// The ISO country code
	IsoCode *string `json:"iso_code"`

	// A list of URLs related to this resource
	Links *map[string]interface{} `json:"links"`

	// Whether dialing to low-risk numbers is enabled
	LowRiskNumbersEnabled *bool `json:"low_risk_numbers_enabled"`

	// The name of the country
	Name *string `json:"name"`

	// The absolute URL of this resource
	Url *string `json:"url"`
}

// VoiceV1DialingPermissionsDialingPermissionsCountryInstance defines model for voice.v1.dialing_permissions.dialing_permissions_country-instance.
type VoiceV1DialingPermissionsDialingPermissionsCountryInstance struct {
	// The name of the continent in which the country is located
	Continent *string `json:"continent"`

	// The E.164 assigned country codes(s)
	CountryCodes *[]string `json:"country_codes"`

	// Whether dialing to high-risk special services numbers is enabled
	HighRiskSpecialNumbersEnabled *bool `json:"high_risk_special_numbers_enabled"`

	// Whether dialing to high-risk toll fraud numbers is enabled, else `false`
	HighRiskTollfraudNumbersEnabled *bool `json:"high_risk_tollfraud_numbers_enabled"`

	// The ISO country code
	IsoCode *string `json:"iso_code"`

	// A list of URLs related to this resource
	Links *map[string]interface{} `json:"links"`

	// Whether dialing to low-risk numbers is enabled
	LowRiskNumbersEnabled *bool `json:"low_risk_numbers_enabled"`

	// The name of the country
	Name *string `json:"name"`

	// The absolute URL of this resource
	Url *string `json:"url"`
}

// VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes defines model for voice.v1.dialing_permissions.dialing_permissions_country.dialing_permissions_hrs_prefixes.
type VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes struct {
	// A prefix that includes the E.164 assigned country code
	Prefix *string `json:"prefix"`
}

// VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate defines model for voice.v1.dialing_permissions.dialing_permissions_country_bulk_update.
type VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate struct {
	// The number of countries updated
	UpdateCount *int `json:"update_count"`

	// A URL encoded JSON array of update objects
	UpdateRequest *string `json:"update_request"`
}

// VoiceV1DialingPermissionsDialingPermissionsSettings defines model for voice.v1.dialing_permissions.dialing_permissions_settings.
type VoiceV1DialingPermissionsDialingPermissionsSettings struct {
	// `true` if the sub-account will inherit voice dialing permissions from the Master Project; otherwise `false`
	DialingPermissionsInheritance *bool `json:"dialing_permissions_inheritance"`

	// The absolute URL of this resource
	Url *string `json:"url"`
}

// VoiceV1IpRecord defines model for voice.v1.ip_record.
type VoiceV1IpRecord struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid"`

	// An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32.
	CidrPrefixLength *int `json:"cidr_prefix_length"`

	// The RFC 2822 date and time in GMT that the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The RFC 2822 date and time in GMT that the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The string that you assigned to describe the resource
	FriendlyName *string `json:"friendly_name"`

	// An IP address in dotted decimal notation, IPv4 only.
	IpAddress *string `json:"ip_address"`

	// The unique string that identifies the resource
	Sid *string `json:"sid"`

	// The absolute URL of the resource
	Url *string `json:"url"`
}

// VoiceV1SourceIpMapping defines model for voice.v1.source_ip_mapping.
type VoiceV1SourceIpMapping struct {
	// The RFC 2822 date and time in GMT that the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The RFC 2822 date and time in GMT that the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The unique string that identifies an IP Record
	IpRecordSid *string `json:"ip_record_sid"`

	// The unique string that identifies the resource
	Sid *string `json:"sid"`

	// The unique string that identifies a SIP Domain
	SipDomainSid *string `json:"sip_domain_sid"`

	// The absolute URL of the resource
	Url *string `json:"url"`
}

// ListByocTrunkParams defines parameters for ListByocTrunk.
type ListByocTrunkParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}

// ListConnectionPolicyParams defines parameters for ListConnectionPolicy.
type ListConnectionPolicyParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}

// ListConnectionPolicyTargetParams defines parameters for ListConnectionPolicyTarget.
type ListConnectionPolicyTargetParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}

// ListDialingPermissionsCountryParams defines parameters for ListDialingPermissionsCountry.
type ListDialingPermissionsCountryParams struct {
	// Filter to retrieve the country permissions by specifying the [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
	IsoCode *string `json:"IsoCode,omitempty"`

	// Filter to retrieve the country permissions by specifying the continent
	Continent *string `json:"Continent,omitempty"`

	// Filter the results by specified [country codes](https://www.itu.int/itudoc/itu-t/ob-lists/icc/e164_763.html)
	CountryCode *string `json:"CountryCode,omitempty"`

	// Filter to retrieve the country permissions with dialing to low-risk numbers enabled. Can be: `true` or `false`.
	LowRiskNumbersEnabled *bool `json:"LowRiskNumbersEnabled,omitempty"`

	// Filter to retrieve the country permissions with dialing to high-risk special service numbers enabled. Can be: `true` or `false`
	HighRiskSpecialNumbersEnabled *bool `json:"HighRiskSpecialNumbersEnabled,omitempty"`

	// Filter to retrieve the country permissions with dialing to high-risk [toll fraud](https://www.twilio.com/learn/voice-and-video/toll-fraud) numbers enabled. Can be: `true` or `false`.
	HighRiskTollfraudNumbersEnabled *bool `json:"HighRiskTollfraudNumbersEnabled,omitempty"`

	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}

// ListDialingPermissionsHrsPrefixesParams defines parameters for ListDialingPermissionsHrsPrefixes.
type ListDialingPermissionsHrsPrefixesParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}

// ListIpRecordParams defines parameters for ListIpRecord.
type ListIpRecordParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}

// ListSourceIpMappingParams defines parameters for ListSourceIpMapping.
type ListSourceIpMappingParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}
