// Package fax provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/faetools/devtool version (devel) DO NOT EDIT.
package fax

import (
	"time"
)

const (
	AccountSid_authTokenScopes = "accountSid_authToken.Scopes"
)

// Defines values for FaxV1FaxDirection.
const (
	FaxV1FaxDirectionInbound  FaxV1FaxDirection = "inbound"
	FaxV1FaxDirectionOutbound FaxV1FaxDirection = "outbound"
)

// Defines values for FaxV1FaxQuality.
const (
	FaxV1FaxQualityFine      FaxV1FaxQuality = "fine"
	FaxV1FaxQualityStandard  FaxV1FaxQuality = "standard"
	FaxV1FaxQualitySuperfine FaxV1FaxQuality = "superfine"
)

// Defines values for FaxV1FaxStatus.
const (
	FaxV1FaxStatusBusy       FaxV1FaxStatus = "busy"
	FaxV1FaxStatusCanceled   FaxV1FaxStatus = "canceled"
	FaxV1FaxStatusDelivered  FaxV1FaxStatus = "delivered"
	FaxV1FaxStatusFailed     FaxV1FaxStatus = "failed"
	FaxV1FaxStatusNoAnswer   FaxV1FaxStatus = "no-answer"
	FaxV1FaxStatusProcessing FaxV1FaxStatus = "processing"
	FaxV1FaxStatusQueued     FaxV1FaxStatus = "queued"
	FaxV1FaxStatusReceived   FaxV1FaxStatus = "received"
	FaxV1FaxStatusReceiving  FaxV1FaxStatus = "receiving"
	FaxV1FaxStatusSending    FaxV1FaxStatus = "sending"
)

// FaxV1Fax defines model for fax.v1.fax.
type FaxV1Fax struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid"`

	// The API version used to transmit the fax
	ApiVersion *string `json:"api_version"`

	// The ISO 8601 formatted date and time in GMT when the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The ISO 8601 formatted date and time in GMT when the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The direction of the fax
	Direction *FaxV1FaxDirection `json:"direction"`

	// The time it took to transmit the fax
	Duration *int `json:"duration"`

	// The number the fax was sent from
	From *string `json:"from"`

	// The URLs of the fax's related resources
	Links *map[string]interface{} `json:"links"`

	// The SID of the FaxMedia resource that is associated with the Fax
	MediaSid *string `json:"media_sid"`

	// The Twilio-hosted URL that can be used to download fax media
	MediaUrl *string `json:"media_url"`

	// The number of pages contained in the fax document
	NumPages *int `json:"num_pages"`

	// The fax transmission price
	Price *float32 `json:"price"`

	// The ISO 4217 currency used for billing
	PriceUnit *string `json:"price_unit"`

	// The quality of the fax
	Quality *FaxV1FaxQuality `json:"quality"`

	// The unique string that identifies the resource
	Sid *string `json:"sid"`

	// The status of the fax
	Status *FaxV1FaxStatus `json:"status"`

	// The phone number that received the fax
	To *string `json:"to"`

	// The absolute URL of the fax resource
	Url *string `json:"url"`
}

// The direction of the fax
type FaxV1FaxDirection string

// The quality of the fax
type FaxV1FaxQuality string

// The status of the fax
type FaxV1FaxStatus string

// FaxV1FaxFaxMedia defines model for fax.v1.fax.fax_media.
type FaxV1FaxFaxMedia struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid"`

	// The content type of the stored fax media
	ContentType *string `json:"content_type"`

	// The ISO 8601 date and time in GMT when the resource was created
	DateCreated *time.Time `json:"date_created"`

	// The ISO 8601 date and time in GMT when the resource was last updated
	DateUpdated *time.Time `json:"date_updated"`

	// The SID of the fax the FaxMedia resource is associated with
	FaxSid *string `json:"fax_sid"`

	// The unique string that identifies the resource
	Sid *string `json:"sid"`

	// The absolute URL of the FaxMedia resource
	Url *string `json:"url"`
}

// ListFaxParams defines parameters for ListFax.
type ListFaxParams struct {
	// Retrieve only those faxes sent from this phone number, specified in [E.164](https://www.twilio.com/docs/glossary/what-e164) format.
	From *string `json:"From,omitempty"`

	// Retrieve only those faxes sent to this phone number, specified in [E.164](https://www.twilio.com/docs/glossary/what-e164) format.
	To *string `json:"To,omitempty"`

	// Retrieve only those faxes with a `date_created` that is before or equal to this value, specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	DateCreatedOnOrBefore *time.Time `json:"DateCreatedOnOrBefore,omitempty"`

	// Retrieve only those faxes with a `date_created` that is later than this value, specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	DateCreatedAfter *time.Time `json:"DateCreatedAfter,omitempty"`

	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}

// ListFaxMediaParams defines parameters for ListFaxMedia.
type ListFaxMediaParams struct {
	// How many resources to return in each list page. The default is 50, and the maximum is 1000.
	PageSize *int `json:"PageSize,omitempty"`
}
